---
title: "Plotly"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

```

```{r, include = FALSE}
##load data
data(rest_inspec)
rest_inspec

```

```{r, include = FALSE}
set.seed(1)

rest_inspec = 
  rest_inspec %>%
  separate(inspection_date, c("year","month","day"), sep = "-") %>%
  select(
         boro, building, cuisine_description, dba, score, street, zipcode, grade, year) %>%
  filter(
    !is.na(score),
    boro == "MANHATTAN",
    grade %in% c("A", "B")
  ) 
  

rest_inspec
  
```

```{r}
##make a boxplot show the scores of different kind of cuisine types in manhattan
rest_inspec %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>%
  plot_ly(y  = ~score, color = ~cuisine_description, type = "box", colors = "Set2")

```

```{r}
##make a bar plot showing number of restaurants in each types of cuisine in manhattan
rest_inspec %>%
  count(cuisine_description) %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>%
  plot_ly(x = ~cuisine_description, y = ~n, type = "bar")

```

```{r}
##make a line plot showing the number of restaurant graded as "A" from each year and see the trends by using the line connect them together
rest_inspec %>%
  mutate(year = as.integer(year)) %>%
  group_by(year, grade) %>%
  summarize(n = n()) %>%
  filter(grade == "A") %>%
  ungroup() %>%
  plot_ly(x = ~year, y = ~n, type = "scatter", mode = "lines+markers")
```